# Generated by Django 5.0.5 on 2024-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('coverImage', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('companyPage', models.URLField()),
                ('username', models.CharField(unique=True)),
            ],
        ),
    ]
