# Generated by Django 5.0.5 on 2024-05-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_logo_alter_company_username'),
        ('company', '0004_alter_company_username'),
    ]

    operations = [
    ]
