# Generated by Django 5.0.5 on 2024-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_coverimage_alter_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
