# Generated by Django 5.0.5 on 2024-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_coverimage_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, default='https://img.freepik.com/free-vector/green-glowing-background_1035-3301.jpg?w=740&t=st=1715254207~exp=1715254807~hmac=a7440325379fbd7737e8bd2d645f9a37eee46c00daf28062cad5a09bb36191e0', max_length=999),
        ),
    ]
