# Generated by Django 5.0.5 on 2024-05-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_remove_recommendations_applicant_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverLetter', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('houseNr', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('postalCode', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=8)),
                ('applyDate', models.DateField()),
                ('resultDate', models.DateField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicantcountry')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.IntegerField(blank=True)),
                ('allowedToContact', models.BooleanField()),
                ('role', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
