# Generated by Django 5.0.5 on 2024-05-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_remove_recommendations_applicant_and_more'),
        ('job', '0002_application_experiences_recommendations_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
