# Generated by Django 5.0.5 on 2024-05-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_application_resultdate_alter_experience_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
