# Generated by Django 5.0.5 on 2024-05-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_application_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
