# Generated by Django 5.0.5 on 2024-05-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_experience_job_recommendation_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='applied_job',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='applied_job',
        ),
    ]
