# Generated by Django 5.0.5 on 2024-05-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_experience_applied_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.RemoveField(
            model_name='application',
            name='houseNr',
        ),
        migrations.RemoveField(
            model_name='application',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='application',
            name='street',
        ),
    ]
