<<<<<<< Updated upstream
# Generated by Django 5.0.6 on 2024-05-14 17:53
=======
# Generated by Django 5.0.6 on 2024-05-14 17:57
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_alter_application_resultdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='allowedToContact',
<<<<<<< Updated upstream
            field=models.BooleanField(default=False),
=======
            field=models.BooleanField(blank=True, default=False),
>>>>>>> Stashed changes
        ),
    ]
