# Generated by Django 5.0.5 on 2024-05-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_recommendation_allowedtocontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
