# Generated by Django 5.0.5 on 2024-05-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_delete_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='allowedToContact',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
