# Generated by Django 5.0.5 on 2024-05-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicantcountry'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='houseNr',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postalCode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Experiences',
        ),
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
