# Generated by Django 5.0.5 on 2024-05-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_alter_applicant_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantEduction',
        ),
    ]
