# Generated by Django 5.0.5 on 2024-05-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_rename_dateend_applicanteduction_end_and_more'),
        ('applicant', '0012_alter_applicant_photo'),
    ]

    operations = [
    ]
