# Generated by Django 5.0.5 on 2024-05-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0013_merge_20240510_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='username',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='aboutMe',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
