# Generated by Django 5.0.5 on 2024-05-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_remove_applicant_username_alter_applicant_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='aboutMe',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicantcountry'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='houseNr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postalCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
