# Generated by Django 5.0.5 on 2024-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_rename_applicanteduction_applicanteducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='fieldOfStudy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='start',
            field=models.DateField(blank=True),
        ),
    ]
