# Generated by Django 5.0.5 on 2024-05-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0018_alter_applicant_aboutme_alter_applicant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicanteducation',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
