# Generated by Django 5.0.5 on 2024-05-15 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0020_rename_applicanteducation_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(default=datetime.date(2024, 5, 15)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='fieldOfStudy',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(default=datetime.date(2024, 5, 15)),
            preserve_default=False,
        ),
    ]
